security:
  oauth2:
    client:
      clientId: fal8zh2u859tgnqg4w0tgoqwq8m7ef

application:
  frontEndUrl: https://beta.bountystreamer.gg
  environment: Beta

spring:
  redis:
    host: bet-st-x776hjs3fk4j.e1fohh.0001.use1.cache.amazonaws.com

paypal:
  clientId: AV1uglYayHqWC42h0U24puljHEfM6qA6wLm0_ZxrTb2vw7nLQCqKXCUCEebvc5cso8CcAnBtncTLVitj
  mode: live