security:
  oauth2:
    client:
      clientId: fal8zh2u859tgnqg4w0tgoqwq8m7ef

application:
  frontEndUrl: https://beta.bountystreamer.gg
  environment: Beta

spring:
  redis:
    host: bet-st-x776hjs3fk4j.e1fohh.0001.use1.cache.amazonaws.com

paypal:
  clientId: AVbr-mNnSiaEKeAa97MPVerIi_G18U8GMqq8XyjXvAfRKH2bLhMy_Ue3XOtdNyjWScSalu8JoN3YJrnP
  mode: sandbox

twitch:
  whiteListedAccounts: nckackerman, M1sterc001guy, vgame18