server:
  port: 8070

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/streamercontractsdb
    username: postgres
    password: changeme
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        temp:
          # Workaround. see: https://stackoverflow.com/questions/49683434/spring-boot-app-fails-method-org-postgresql-jdbc4-jdbc4connection-createclob-i
          use_jdbc_metadata_defaults: false
        ddl-auto: validate

security:
  oauth2:
    client:
      clientId: asuomro2120fbgjzwimsunv4fl9hqw
      clientSecret: z6jff6u1x1ukpsicv6cmgdnd7tcuy4
      accessTokenUri: https://api.twitch.tv/api/oauth2/token
      userAuthorizationUri: https://id.twitch.tv/oauth2/authorize
      clientAuthenticationScheme: form
      scope:
        - openid
    resource:
      userInfoUri: https://api.twitch.tv/helix/users
      preferTokenInfo: true

frontEndUrl: http://localhost:3000
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
