server:
  port: 8070
  ssl:
    key-store: ${STREAMER_CONTRACTS_KEY_STORE_URL}
    key-store-password: password
    key-store-type: JKS
    key-alias: tomcat

spring:
#  Redis session config
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379

#  Database config
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/streamercontractsdb
    username: application_user
    password: password
    validation-query: SELECT 1
    initSQL: SET NAMES 'utf8mb4'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        temp:
          # Workaround. see: https://stackoverflow.com/questions/49683434/spring-boot-app-fails-method-org-postgresql-jdbc4-jdbc4connection-createclob-i
          use_jdbc_metadata_defaults: false
        ddl-auto: validate

twitch:
  # Need both http and https for the twitch devRig
  frontEndUrls: https://localhost.rig.twitch.tv:8080, http://localhost.rig.twitch.tv:8080
  extension:
    client: n79uq3pvee208imhrzr14um2rboiwv
    secret: ncstDxsrg9Sc872otJT8Z+xt75rW8VpCy9F1rKO/vNU=
    jwtHeader: Authorization

security:
  # SSL config
  require-ssl: true

  # Oauth config
  oauth2:
    client:
      clientId: asuomro2120fbgjzwimsunv4fl9hqw
      clientSecret: z6jff6u1x1ukpsicv6cmgdnd7tcuy4
      accessTokenUri: https://api.twitch.tv/api/oauth2/token
      userAuthorizationUri: https://id.twitch.tv/oauth2/authorize
      clientAuthenticationScheme: form
      scope:
        - openid
    resource:
      userInfoUri: https://api.twitch.tv/helix/users
      preferTokenInfo: true

application:
  frontEndUrl: https://localhost:3010
  environment: Dev

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
