# This is an appspec.yml template file for use with an EC2/On-Premises deployment in AWS CodeDeploy.
# For help completing this file, see the "AppSpec File Reference" in the
#   "AWS CodeDeploy User Guide" at
#   http://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/streamercontracts
permissions:
  - object: /var/www/streamercontracts
    owner: ec2-user
    pattern: "**"
    mode: 775
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 60
  ApplicationStart:
    - location: start.sh
      timeout: 60