#Prequisits
#1) Github repository hosting SpringBoot Application
#2) Run hosts.yml and retrieve AutoScalingGroup Names for Beta and Prod
AWSTemplateFormatVersion: 2010-09-09
Description: Builds a codepipeline for managing AWS deployments from a github repository
Parameters:
  GitHubRepoOwner:
    Type: String
    Description: ex - NateMoeller
    Default: NateMoeller
  GitHubRepoName:
    Type: String
    Description: ex - StreamerContracts
    Default: StreamerContracts
  GitHubRepoBranch:
    Type: String
    Description: ex - master
    Default: master
  GitHubRepoOAuthToken:
    Type: String
    Description: Generate a github personal access token (with least required privlidges) and paste its value in here. See - https://github.com/settings/tokens
  S3WebHostBucketName:
    Type: String
    Description: Must match domain name (likely registered in Route 53)
    Default: bountystreamer.gg
  BetaAutoScalingGroup:
    Type: String
    Description: Must match AutoScalingGroup for Beta. Check AWS for this value
    Default: BetaBountyStreamerHosts-StreamerContractsApiAutoScalingGroup-PLCH7OJVG1EQ
  ProdAutoScalingGroup:
    Type: String
    Description: Must match AutoScalingGroup for Beta. Check AWS for this value
    Default: ProdBountyStreamerHosts-StreamerContractsApiAutoScalingGroup-1LX4CWHGUR80V

Resources:
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildServiceRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
              Effect: Allow
            - Action:
              - s3:PutObject
              - s3:GetObject
              - s3:GetObjectVersion
              Resource: "*"
              Effect: Allow
            - Action:
              - s3:DeleteObject
              Resource:
              - !GetAtt BetaStreamerContractsWebHostBucket.Arn
              - !GetAtt ProdStreamerContractsWebHostBucket.Arn
              Effect: Allow
            - Action:
              - ssm:GetParameters
              Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/CodeBuild/*
              Effect: Allow

  StreamerContractsApiCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Description: StreamerContracts CodeBuild
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/java:openjdk-8
        Type: LINUX_CONTAINER
      Name: StreamerContractsCodeBuild
      ServiceRole: !Ref CodeBuildServiceRole
      Source:
        Type: CODEPIPELINE
        BuildSpec: dev_ops/infrastructure/code_build/build_spec.yml
      TimeoutInMinutes: 10

  BetaStreamerContractsWebCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Description: StreamerContracts CodeBuild
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
        - Name: S3_WEB_HOST_BUCKET
          Type: PLAINTEXT
          Value: !Sub s3://beta.${S3WebHostBucketName}
        - Name: WEB_BUILD_COMMAND
          Type: PLAINTEXT
          Value: buildBetaAssets
        Image: aws/codebuild/java:openjdk-8
        Type: LINUX_CONTAINER
      Name: BetaStreamerContractsWebCodeBuild
      ServiceRole: !Ref CodeBuildServiceRole
      Source:
        Type: CODEPIPELINE
        BuildSpec: dev_ops/infrastructure/code_build/build_spec_web.yml
      TimeoutInMinutes: 10

  ProdStreamerContractsWebCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Description: StreamerContracts CodeBuild
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
        - Name: S3_WEB_HOST_BUCKET
          Type: PLAINTEXT
          Value: !Sub s3://${S3WebHostBucketName}
        - Name: WEB_BUILD_COMMAND
          Type: PLAINTEXT
          Value: buildProdAssets
        Image: aws/codebuild/java:openjdk-8
        Type: LINUX_CONTAINER
      Name: ProdStreamerContractsWebCodeBuild
      ServiceRole: !Ref CodeBuildServiceRole
      Source:
        Type: CODEPIPELINE
        BuildSpec: dev_ops/infrastructure/code_build/build_spec_web.yml
      TimeoutInMinutes: 10

  CodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
            Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeDeployServiceRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Action:
              - autoscaling:CompleteLifecycleAction
              - autoscaling:DeleteLifecycleHook
              - autoscaling:DescribeAutoScalingGroups
              - autoscaling:DescribeLifecycleHooks
              - autoscaling:PutLifecycleHook
              - autoscaling:RecordLifecycleActionHeartbeat
              - autoscaling:CreateAutoScalingGroup
              - autoscaling:UpdateAutoScalingGroup
              - autoscaling:EnableMetricsCollection
              - autoscaling:DescribeAutoScalingGroups
              - autoscaling:DescribePolicies
              - autoscaling:DescribeScheduledActions
              - autoscaling:DescribeNotificationConfigurations
              - autoscaling:DescribeLifecycleHooks
              - autoscaling:SuspendProcesses
              - autoscaling:ResumeProcesses
              - autoscaling:AttachLoadBalancers
              - autoscaling:PutScalingPolicy
              - autoscaling:PutScheduledUpdateGroupAction
              - autoscaling:PutNotificationConfiguration
              - autoscaling:PutLifecycleHook
              - autoscaling:DescribeScalingActivities
              - autoscaling:DeleteAutoScalingGroup
              - ec2:DescribeInstances
              - ec2:DescribeInstanceStatus
              - ec2:TerminateInstances
              - tag:GetTags
              - tag:GetResources
              - sns:Publish
              - cloudwatch:DescribeAlarms
              - cloudwatch:PutMetricAlarm
              - elasticloadbalancing:DescribeLoadBalancers
              - elasticloadbalancing:DescribeInstanceHealth
              - elasticloadbalancing:RegisterInstancesWithLoadBalancer
              - elasticloadbalancing:DeregisterInstancesFromLoadBalancer
              - elasticloadbalancing:DescribeTargetGroups
              - elasticloadbalancing:DescribeTargetHealth
              - elasticloadbalancing:RegisterTargets
              - elasticloadbalancing:DeregisterTargets
              Resource: "*"
              Effect: Allow

  StreamerContractsCodeDeployApiApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ComputePlatform: Server

  BetaStreamerContractsCodeDeployApiDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      AutoScalingGroups:
        # Must match AutoScalingGroupName created in hosts.yml
        - !Ref BetaAutoScalingGroup
      ApplicationName: !Ref StreamerContractsCodeDeployApiApplication
      DeploymentConfigName: CodeDeployDefault.AllAtOnce
      DeploymentStyle:
        DeploymentOption: WITHOUT_TRAFFIC_CONTROL
        DeploymentType: IN_PLACE
      ServiceRoleArn: !GetAtt CodeDeployServiceRole.Arn

  ProdStreamerContractsCodeDeployApiDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      AutoScalingGroups:
        # Must match AutoScalingGroupName created in hosts.yml
        - !Ref ProdAutoScalingGroup
      ApplicationName: !Ref StreamerContractsCodeDeployApiApplication
      DeploymentConfigName: CodeDeployDefault.AllAtOnce
      DeploymentStyle:
        DeploymentOption: WITHOUT_TRAFFIC_CONTROL
        DeploymentType: IN_PLACE
      ServiceRoleArn: !GetAtt CodeDeployServiceRole.Arn

  ArtifactStoreS3Location:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AccessControl: Private
      # S3 bucket where codepipeline artifacts are stored. Must be lower case and unique across all S3 buckets.
      BucketName: !Sub codepipeline-artifacts-${S3WebHostBucketName}
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 1
            Status: Enabled
      VersioningConfiguration:
        Status: Enabled

  BetaStreamerContractsWebHostBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      BucketName: !Sub beta.${S3WebHostBucketName}

  BetaStreamerContractsWebHostBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BetaStreamerContractsWebHostBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Action:
          - s3:GetObject
          Resource: !Sub arn:aws:s3:::${BetaStreamerContractsWebHostBucket}/*
          Principal: "*"
          Effect: Allow

  ProdStreamerContractsWebHostBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      BucketName: !Ref S3WebHostBucketName

  ProdStreamerContractsWebHostBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ProdStreamerContractsWebHostBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Action:
          - s3:GetObject
          Resource: !Sub arn:aws:s3:::${ProdStreamerContractsWebHostBucket}/*
          Principal: "*"
          Effect: Allow

  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
            Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelineServiceRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Action:
              - s3:PutObject
              Resource: arn:aws:s3:::codepipeline*
              Effect: Allow
            - Action:
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:GetBucketVersioning
              - codecommit:CancelUploadArchive
              - codecommit:GetBranch
              - codecommit:GetCommit
              - codecommit:GetUploadArchiveStatus
              - codecommit:UploadArchive
              - codedeploy:CreateDeployment
              - codedeploy:GetApplicationRevision
              - codedeploy:GetDeployment
              - codedeploy:GetDeploymentConfig
              - codedeploy:RegisterApplicationRevision
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
              - ec2:*
              - elasticloadbalancing:*
              - autoscaling:*
              - cloudwatch:*
              - s3:*
              - sns:*
              - cloudformation:*
              - rds:*
              - sqs:*
              - ecs:*
              - iam:PassRole
              Resource: "*"
              Effect: Allow

  StreamerContractsCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactStoreS3Location
      DisableInboundStageTransitions:
        - StageName: Prod
          Reason: Transitions to PROD must be manually triggered
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              RunOrder: 1
              ActionTypeId:
                Category: Source
                Provider: GitHub
                Owner: ThirdParty
                Version: 1
              Configuration:
                Owner: !Ref GitHubRepoOwner
                Repo: !Ref GitHubRepoName
                Branch: !Ref GitHubRepoBranch
                OAuthToken: !Ref GitHubRepoOAuthToken
              OutputArtifacts:
                - Name: SourceOutput
        - Name: Build
          Actions:
            - Name: BuildAction-Api
              RunOrder: 1
              InputArtifacts:
                - Name: SourceOutput
              ActionTypeId:
                Category: Build
                Provider: CodeBuild
                Owner: AWS
                Version: 1
              Configuration:
                ProjectName: !Ref StreamerContractsApiCodeBuild
              OutputArtifacts:
                - Name: BuildOutput-Api
            - Name: BuildAction-Web
              RunOrder: 1
              InputArtifacts:
                - Name: SourceOutput
              ActionTypeId:
                Category: Build
                Provider: CodeBuild
                Owner: AWS
                Version: 1
              Configuration:
                ProjectName: !Ref BetaStreamerContractsWebCodeBuild
              OutputArtifacts:
                - Name: BuildOutput-Web
        - Name: Beta
          Actions:
            - Name: BetaDeployAction-Api
              RunOrder: 1
              InputArtifacts:
                - Name: BuildOutput-Api
              ActionTypeId:
                Category: Deploy
                Provider: CodeDeploy
                Owner: AWS
                Version: 1
              Configuration:
                ApplicationName: !Ref StreamerContractsCodeDeployApiApplication
                DeploymentGroupName: !Ref BetaStreamerContractsCodeDeployApiDeploymentGroup
            - Name: BetaDeployAction-Web
              RunOrder: 1
              InputArtifacts:
                - Name: SourceOutput
              ActionTypeId:
                Category: Build
                Provider: CodeBuild
                Owner: AWS
                Version: 1
              Configuration:
                ProjectName: !Ref BetaStreamerContractsWebCodeBuild
        - Name: Prod
          Actions:
            - Name: ProdDeployAction-Api
              RunOrder: 1
              InputArtifacts:
                - Name: BuildOutput-Api
              ActionTypeId:
                Category: Deploy
                Provider: CodeDeploy
                Owner: AWS
                Version: 1
              Configuration:
                ApplicationName: !Ref StreamerContractsCodeDeployApiApplication
                DeploymentGroupName: !Ref ProdStreamerContractsCodeDeployApiDeploymentGroup
            - Name: ProdDeployAction-Web
              RunOrder: 1
              InputArtifacts:
                - Name: SourceOutput
              ActionTypeId:
                Category: Build
                Provider: CodeBuild
                Owner: AWS
                Version: 1
              Configuration:
                ProjectName: !Ref ProdStreamerContractsWebCodeBuild