AWSTemplateFormatVersion: 2010-09-09
Description: VPC and Ec2 Instances for StreamerContracts App
Parameters:
  KeyPairName:
    Type: String
    Description: Used to ssh securly onto Ec2 Instance
    Default: streamer-contracts
  StreamerContractsEc2InstanceTags:
    Type: String
    Description: The EC2 tags that are already applied to EC2 instances that you want to include in the deployment group.
    Default: StreamerContracts
  StreamerContractsWebDomain:
    Type: String
    Description: The DomainName that StreamerContracts runs on.
    Default: streamercontracts.co.uk

Resources:
  StreamerContractsVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default

  StreamerContractsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: StreamerContractsSecurityGroup
      GroupDescription: SecurityGroup for EC2 Hosts
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound communication from any port to any port
          FromPort: -1
          IpProtocol: -1
          ToPort: -1
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all inbound communication from any port to any port
          FromPort: -1
          IpProtocol: -1
          ToPort: -1
      VpcId: !Ref StreamerContractsVPC

  StreamerContractsSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1e
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      VpcId: !Ref StreamerContractsVPC

  StreamerContractsSubnetTwo:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1a
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      VpcId: !Ref StreamerContractsVPC

  StreamerContractsInternetGateway:
    Type: AWS::EC2::InternetGateway

  StreamerContractsVpcGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref StreamerContractsInternetGateway
      VpcId: !Ref StreamerContractsVPC

  StreamerContractsRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref StreamerContractsVPC

  StreamerContractsRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref StreamerContractsInternetGateway
      RouteTableId: !Ref StreamerContractsRouteTable

  StreamerContractsSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref StreamerContractsRouteTable
      SubnetId: !Ref StreamerContractsSubnet

  Ec2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      RoleName: StreamerContractsEc2InstanceProfileRole

  StreamerContractsDevAwsUser:
    Type: AWS::IAM::User
    Properties:
      UserName: StreamerContractsDevAwsUser

  StreamerContractsIAMPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Action:
          - s3:Get*
          - s3:List*
          Resource:
            - !Sub arn:aws:s3:::aws-codedeploy-${AWS::Region}/*
            - "*"
          Effect: Allow
        - Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          - logs:DescribeLogStreams
          Resource:
            - arn:aws:logs:*:*:*
          Effect: Allow
      PolicyName: StreamerContractsEc2InstanceProfileRole
      Roles:
        - !Ref Ec2InstanceRole
      Users:
        - !Ref StreamerContractsDevAwsUser

  Ec2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref Ec2InstanceRole
      InstanceProfileName: StreamerContractsEc2InstanceProfile

  StreamerContractsLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: StreamerContractsLoadBalancer
      Scheme: internet-facing
      SecurityGroups:
        - !Ref StreamerContractsSecurityGroup
      Subnets:
        - !Ref StreamerContractsSubnet
        - !Ref StreamerContractsSubnetTwo
      Type: application
      IpAddressType: ipv4

  StreamerContractsLoadBalancerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: api-target-group
      Port: 8070
      Protocol: HTTP
      VpcId: !Ref StreamerContractsVPC

  StreamerContractsLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref StreamerContractsLoadBalancerTargetGroup
          Type: forward
      LoadBalancerArn: !Ref StreamerContractsLoadBalancer
      Port: 80
      Protocol: HTTP

  StreamerContractsApiLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: true
      IamInstanceProfile: !Ref Ec2InstanceProfile
      ImageId: ami-467ca739
      InstanceMonitoring: false
      InstanceType: t2.micro
      KeyName: !Ref KeyPairName
      LaunchConfigurationName: StreamerContractsApiLaunchConfiguration
      SecurityGroups:
        - !Ref StreamerContractsSecurityGroup
      # Logs created while running these commands are saved at /var/log/cloud-init-output.log on ec2 hosts
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum -y update
          yum install -y ruby
          cd /home/ec2-user
          curl -O https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/install
          chmod +x ./install
          ./install auto
          sudo yum -y remove java-1.7.0-openjdk
          sudo yum -y install java-1.8.0
          sudo yum -y install awslogs

  StreamerContractsApiAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: ApiAutoScalingGroup
      DesiredCapacity: 1
      LaunchConfigurationName: !Ref StreamerContractsApiLaunchConfiguration
      TargetGroupARNs:
        - !Ref StreamerContractsLoadBalancerTargetGroup
      MaxSize: 5
      MinSize: 1
      Tags:
        - Key: Name
          Value: !Sub ${StreamerContractsEc2InstanceTags}-Api
          PropagateAtLaunch: true
      VPCZoneIdentifier:
        - !Ref StreamerContractsSubnet

  # You must update your DNS provider to use the nameservers associated with this HostedZone
  StreamerContractsRoute53:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: HostedZone for StreamerContracts
      Name: !Ref StreamerContractsWebDomain

  StreamerContractsWebRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
          DNSName: s3-website-us-east-1.amazonaws.com
          # obtained from here: https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region
          HostedZoneId: Z3AQBSTGFYJSTF
      HostedZoneId: !Ref StreamerContractsRoute53
      # Note: Must EXACTLY match the s3 bucket name that stores website content
      Name: !Sub web.${StreamerContractsWebDomain}
      Type: A

  StreamerContractsApiRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref StreamerContractsRoute53
      Name: !Sub api.${StreamerContractsWebDomain}
      ResourceRecords:
        - !GetAtt StreamerContractsLoadBalancer.DNSName
      TTL: 300
      Type: CNAME

  StreamerContractsDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DB Subnet for StreamerContracts
      # DBSubnetGroupName is stored as lower case string
      DBSubnetGroupName: streamercontractsdbsubnetgroup
      SubnetIds:
        - !Ref StreamerContractsSubnet
        - !Ref StreamerContractsSubnetTwo

  StreamerContractsDBInstance:
    Type: AWS::RDS::DBInstance
    DependsOn: StreamerContractsDBSubnetGroup
    Properties:
      AllocatedStorage: 100
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: streamer-contracts-db
      DBName: StreamerContractsDB
      DBSubnetGroupName: streamercontractsdbsubnetgroup
      PubliclyAccessible: true
      Engine: postgres
      EngineVersion: 9.6
      MasterUsername: StreamerContractsAdmin
      MasterUserPassword: ChangeMe
      Port: 5432
      VPCSecurityGroups:
        - !Ref StreamerContractsSecurityGroup

  StreamerContractsConfigurations:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AccessControl: Private
      # S3 bucket where codepipeline artifacts are stored. Must be lower case and unique across all S3 buckets.
      BucketName: streamer-contracts-application-configurations
      VersioningConfiguration:
        Status: Enabled