version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - bash ./gradlew clean
      - bash ./gradlew web:buildAssets
      - bash ./gradlew build
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - web/build/libs/web-1.0-SNAPSHOT.jar
    - api/build/libs/api-1.0-SNAPSHOT.jar
    - infrastructure/nginx/nginx.conf
    - infrastructure/code_deploy/appspec.yml
    - infrastructure/code_deploy/start.sh
    - infrastructure/code_deploy/before_install.sh
  discard-paths: yes