version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - bash ./gradlew clean
      - bash ./gradlew api:build
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - api/build/libs/api-1.0-SNAPSHOT.jar
    - dev_ops/infrastructure/nginx/nginx-beta.conf
    - dev_ops/infrastructure/code_deploy/appspec.yml
    - dev_ops/infrastructure/code_deploy/start.sh
    - dev_ops/infrastructure/code_deploy/before_install.sh
    - dev_ops/infrastructure/cloud_watch/awslogs_api.conf
    - dev_ops/infrastructure/cloud_watch/awslogs_nginx.conf
  discard-paths: yes