version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - bash ./gradlew clean
      - bash ./gradlew api:build
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - api/build/libs/api-1.0-SNAPSHOT.jar
    - devOps/infrastructure/nginx/nginx-beta.conf
    - devOps/infrastructure/code_deploy/appspec.yml
    - devOps/infrastructure/code_deploy/start.sh
    - devOps/infrastructure/code_deploy/before_install.sh
  discard-paths: yes