version: 0.2

phases:
  install:
    commands:
      - echo Entered the web install phase...
  pre_build:
    commands:
      - echo Entered the web pre_build phase...
  build:
    commands:
      - echo Entered the web build phase...
      - echo Build started on `date`
      - bash ./gradlew web:clean
      - bash ./gradlew web:$WEB_BUILD_COMMAND
      # Must match the bucket name created during code_pipeline.yml
      - aws s3 sync ./web/build/ $S3_WEB_HOST_BUCKET --delete
  post_build:
    commands:
      - echo Entered the web post_build phase...
      - echo web Build completed on `date`