version: 0.2

phases:
  install:
    commands:
      - echo Entered the api install phase...
  pre_build:
    commands:
      - echo Entered the api pre_build phase...
  build:
    commands:
      - echo Entered the api build phase...
      - echo Build started on `date`
      - bash ./gradlew api:clean
      - bash ./gradlew api:test
      - bash ./gradlew api:build
  post_build:
    commands:
      - echo Entered the api post_build phase...
      - echo api Build completed on `date`
artifacts:
  files:
    - api/build/libs/api-1.0-SNAPSHOT.jar
    - dev_ops/infrastructure/code_deploy/appspec.yml
    - dev_ops/infrastructure/code_deploy/start.sh
    - dev_ops/infrastructure/code_deploy/before_install.sh
    - dev_ops/infrastructure/cloud_watch/awslogs_api.conf
    - dev_ops/infrastructure/cloud_watch/awslogs_nginx.conf
  discard-paths: yes